/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_HAL_ADC_H
#define _MOCK_HAL_ADC_H

#include "unity.h"
#include "hal_adc.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void mock_hal_adc_Init(void);
void mock_hal_adc_Destroy(void);
void mock_hal_adc_Verify(void);




#define HAL_ADC_GetValue_Ignore() TEST_FAIL_MESSAGE("HAL_ADC_GetValue requires _IgnoreAndReturn");
#define HAL_ADC_GetValue_IgnoreAndReturn(cmock_retval) HAL_ADC_GetValue_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_ADC_GetValue_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_to_return);
#define HAL_ADC_GetValue_StopIgnore() HAL_ADC_GetValue_CMockStopIgnore()
void HAL_ADC_GetValue_CMockStopIgnore(void);
#define HAL_ADC_GetValue_Expect() TEST_FAIL_MESSAGE("HAL_ADC_GetValue requires _ExpectAndReturn");
#define HAL_ADC_GetValue_ExpectAndReturn(cmock_retval) HAL_ADC_GetValue_CMockExpectAndReturn(__LINE__, cmock_retval)
void HAL_ADC_GetValue_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_to_return);

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
