/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_hal_adc.h"

static const char* CMockString_HAL_ADC_GetValue = "HAL_ADC_GetValue";

typedef struct _CMOCK_HAL_ADC_GetValue_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint16_t ReturnVal;

} CMOCK_HAL_ADC_GetValue_CALL_INSTANCE;

static struct mock_hal_adcInstance
{
  char HAL_ADC_GetValue_IgnoreBool;
  uint16_t HAL_ADC_GetValue_FinalReturn;
  CMOCK_MEM_INDEX_TYPE HAL_ADC_GetValue_CallInstance;
} Mock;


void mock_hal_adc_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.HAL_ADC_GetValue_CallInstance;
  if (Mock.HAL_ADC_GetValue_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_ADC_GetValue);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
}

void mock_hal_adc_Init(void)
{
  mock_hal_adc_Destroy();
}

void mock_hal_adc_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

uint16_t HAL_ADC_GetValue(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_ADC_GetValue_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_ADC_GetValue);
  cmock_call_instance = (CMOCK_HAL_ADC_GetValue_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_ADC_GetValue_CallInstance);
  Mock.HAL_ADC_GetValue_CallInstance = CMock_Guts_MemNext(Mock.HAL_ADC_GetValue_CallInstance);
  if (Mock.HAL_ADC_GetValue_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.HAL_ADC_GetValue_FinalReturn;
    Mock.HAL_ADC_GetValue_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void HAL_ADC_GetValue_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_ADC_GetValue_CALL_INSTANCE));
  CMOCK_HAL_ADC_GetValue_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_ADC_GetValue_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_ADC_GetValue_CallInstance = CMock_Guts_MemChain(Mock.HAL_ADC_GetValue_CallInstance, cmock_guts_index);
  Mock.HAL_ADC_GetValue_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.HAL_ADC_GetValue_IgnoreBool = (char)1;
}

void HAL_ADC_GetValue_CMockStopIgnore(void)
{
  if(Mock.HAL_ADC_GetValue_IgnoreBool)
    Mock.HAL_ADC_GetValue_CallInstance = CMock_Guts_MemNext(Mock.HAL_ADC_GetValue_CallInstance);
  Mock.HAL_ADC_GetValue_IgnoreBool = (char)0;
}

void HAL_ADC_GetValue_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_ADC_GetValue_CALL_INSTANCE));
  CMOCK_HAL_ADC_GetValue_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_ADC_GetValue_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_ADC_GetValue_CallInstance = CMock_Guts_MemChain(Mock.HAL_ADC_GetValue_CallInstance, cmock_guts_index);
  Mock.HAL_ADC_GetValue_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

