/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_HAL_GPIO_H
#define _MOCK_HAL_GPIO_H

#include "unity.h"
#include "hal_gpio.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void mock_hal_gpio_Init(void);
void mock_hal_gpio_Destroy(void);
void mock_hal_gpio_Verify(void);




#define HAL_GPIO_SetPin_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("HAL_GPIO_SetPin requires _Ignore (not AndReturn)");
#define HAL_GPIO_SetPin_Ignore() HAL_GPIO_SetPin_CMockIgnore()
void HAL_GPIO_SetPin_CMockIgnore(void);
#define HAL_GPIO_SetPin_StopIgnore() HAL_GPIO_SetPin_CMockStopIgnore()
void HAL_GPIO_SetPin_CMockStopIgnore(void);
#define HAL_GPIO_SetPin_ExpectAndReturn(pin, level, cmock_retval) TEST_FAIL_MESSAGE("HAL_GPIO_SetPin requires _Expect (not AndReturn)");
#define HAL_GPIO_SetPin_Expect(pin, level) HAL_GPIO_SetPin_CMockExpect(__LINE__, pin, level)
void HAL_GPIO_SetPin_CMockExpect(UNITY_LINE_TYPE cmock_line, gpio_pin_t pin, gpio_level_t level);

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
