/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_hal_gpio.h"

static const char* CMockString_HAL_GPIO_SetPin = "HAL_GPIO_SetPin";
static const char* CMockString_level = "level";
static const char* CMockString_pin = "pin";

typedef struct _CMOCK_HAL_GPIO_SetPin_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  gpio_pin_t Expected_pin;
  gpio_level_t Expected_level;

} CMOCK_HAL_GPIO_SetPin_CALL_INSTANCE;

static struct mock_hal_gpioInstance
{
  char HAL_GPIO_SetPin_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE HAL_GPIO_SetPin_CallInstance;
} Mock;


void mock_hal_gpio_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.HAL_GPIO_SetPin_CallInstance;
  if (Mock.HAL_GPIO_SetPin_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_GPIO_SetPin);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
}

void mock_hal_gpio_Init(void)
{
  mock_hal_gpio_Destroy();
}

void mock_hal_gpio_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void HAL_GPIO_SetPin(gpio_pin_t pin, gpio_level_t level)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_GPIO_SetPin_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_GPIO_SetPin);
  cmock_call_instance = (CMOCK_HAL_GPIO_SetPin_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_GPIO_SetPin_CallInstance);
  Mock.HAL_GPIO_SetPin_CallInstance = CMock_Guts_MemNext(Mock.HAL_GPIO_SetPin_CallInstance);
  if (Mock.HAL_GPIO_SetPin_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_HAL_GPIO_SetPin,CMockString_pin);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(&cmock_call_instance->Expected_pin, &pin, sizeof(gpio_pin_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_HAL_GPIO_SetPin,CMockString_level);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(&cmock_call_instance->Expected_level, &level, sizeof(gpio_level_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_HAL_GPIO_SetPin(CMOCK_HAL_GPIO_SetPin_CALL_INSTANCE* cmock_call_instance, gpio_pin_t pin, gpio_level_t level);
void CMockExpectParameters_HAL_GPIO_SetPin(CMOCK_HAL_GPIO_SetPin_CALL_INSTANCE* cmock_call_instance, gpio_pin_t pin, gpio_level_t level)
{
  memcpy((void*)(&cmock_call_instance->Expected_pin), (const void*)(&pin),
         sizeof(gpio_pin_t[sizeof(pin) == sizeof(gpio_pin_t) ? 1 : -1])); /* add gpio_pin_t to :treat_as_array if this causes an error */
  memcpy((void*)(&cmock_call_instance->Expected_level), (const void*)(&level),
         sizeof(gpio_level_t[sizeof(level) == sizeof(gpio_level_t) ? 1 : -1])); /* add gpio_level_t to :treat_as_array if this causes an error */
}

void HAL_GPIO_SetPin_CMockIgnore(void)
{
  Mock.HAL_GPIO_SetPin_IgnoreBool = (char)1;
}

void HAL_GPIO_SetPin_CMockStopIgnore(void)
{
  Mock.HAL_GPIO_SetPin_IgnoreBool = (char)0;
}

void HAL_GPIO_SetPin_CMockExpect(UNITY_LINE_TYPE cmock_line, gpio_pin_t pin, gpio_level_t level)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_GPIO_SetPin_CALL_INSTANCE));
  CMOCK_HAL_GPIO_SetPin_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_GPIO_SetPin_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_GPIO_SetPin_CallInstance = CMock_Guts_MemChain(Mock.HAL_GPIO_SetPin_CallInstance, cmock_guts_index);
  Mock.HAL_GPIO_SetPin_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_HAL_GPIO_SetPin(cmock_call_instance, pin, level);
}

